% Clean up script for the Automate Real-Time Testing for Forward Vehicle
% Sensor Fusion Example
%
% This script cleans up the RTForwardVehicleSensorFusionHost.slx model. It
% is triggered by the CloseFcn callback.
%
%   This is a helper script for example purposes and may be removed or
%   modified in the future.

%   Copyright 2021 The MathWorks, Inc.

clearBuses({...
    'BusRadar',...
    'BusTrackerJPDA',...
    'BusTrackerJPDATracks',...
    'BusVehiclePose',...
    'BusVision',...
    'BusVisionDetections',...
    'BusVisionDetectionsMeasurementParameters',...
    'BusVisionDetectionsObjectAttributes',...
     'BusActors1',...
     'BusLaneDetections1',...
     'BusLaneDetections1LaneBoundaries',...
     'BusObjectDetections',...
     'BusObjectDetections1',...
     'BusObjectDetections1Detections'});

clear alpha
clear assessment
clear camera
clear cutOffDistance
clear order
clear radar
clear scenario
clear switchingPenalty
clear Ts
clear vehSim3D
clear maxNumRadarDets
clear maxNumTracks
clear maxNumVisionDets

function clearBuses(buses)
matlabshared.tracking.internal.DynamicBusUtilities.removeDefinition(buses);
end
