% Clean up script for the Forward Vehicle Sensor Fusion Example
%
% This script cleans up the Forward vehicle sensor example model. It is
% triggered by the CloseFcn callback.
%
%   This is a helper script for example purposes and may be removed or
%   modified in the future.

%   Copyright 2020-2022 The MathWorks, Inc.

clearBuses({ ...
    'BusActors1',...
    'BusDetectionConcatenation1',...
    'BusDetectionConcatenation1Detections',...
    'BusDetectionConcatenation1DetectionsMeasurementParameters',...
    'BusObjectDetections1',...
    'BusObjectDetections1Detections',...
    'BusRadar',...
    'BusVehiclePose',...
    'BusVision',...
    'BusVisionDetections',...
    'BusVisionDetectionsMeasurementParameters',...
    'BusVisionDetectionsObjectAttributes',...
    'BusLaneDetections1',...
    'BusLaneDetections1LaneBoundaries',...
    'BusActors1Actors',...
    'BusRadarDetections',...
    'BusRadarDetectionsMeasurementParameters',...
    'BusRadarDetectionsObjectAttributes',...
    'BusSimulation3DActors1',...
    'BusVisionDetectionsDouble',...
    'BusVisionDetectionsMeasurementParametersDouble',...
    'BusVisionDetectionsObjectAttributesDouble',...
    'BusVisionDouble',...
    'BusObjectDetections',...
    'BusTrackerJPDA',...
    'BusTrackerJPDATracks'});

clear 'assigThresh';
clear camera;
clear M;
clear N;
clear numSensors;
clear numTracks;
clear radar;
clear scenario;
clear Ts;
clear Epsilon
clear MinNumPoints
clear P
clear R
clear alpha
clear cutOffDistance
clear order 
clear switchingPenalty
clear vehSim3D
clear assessment
clear TimeDataType
clear numRadarDetections
clear numObjectDetections

function clearBuses(buses)
matlabshared.tracking.internal.DynamicBusUtilities.removeDefinition(buses);
end