% Clean up script for the Generate Code for Lane marker Detector Example
%
% This script cleans up the LaneMarkerDetectorTestBench model. It
% is triggered by the CloseFcn callback.
%
% This is a helper script for example purposes and may be removed or
% modified in the future.

%   Copyright 2020-2023 The MathWorks, Inc.

clearBuses({ ...
    'BusActors1',...
    'BusActors1Actors',...
    'BusLaneBoundaries',...
    'BusLaneBoundariesLaneBoundaries',...
    'BusLaneBoundaries1',...
    'BusLaneBoundaries1LaneBoundaries',...
    'BusVehicleToWorldActors1',...
    'BusVehicleToWorldActors1Actors',...
    'LaneSensor',...
    'LaneSensorBoundaries'});

clear assessment
clear Ts
clear camera
clear scenario
clear scenarioFcnName
clear vehSim3D

function clearBuses(buses)
matlabshared.tracking.internal.DynamicBusUtilities.removeDefinition(buses);
end
